import { Marker } from "mapbox-gl";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";


import ReactMapGL from "react-map-gl";

import Auth from "./auth";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const Token = "pk.eyJ1IjoiYm91aHppbGExIiwiYSI6ImNsbmRvNXd0MDA1emcyam9obTR5ZWd1MnIifQ.am_ZMozQCpGPyQD0u3fuAQ";

  const [viewPort, setViewPort] = useState({
    latitude: 37.7577,
    longitude: -122.4376,
    zoom: 6,
  });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" ">
      <Auth />
       

      
      </main>
    </>
  );
}
