import { AuthButton } from "@/components/AuthButton";
import { FiltersButton } from "@/components/FiltersButton";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import { SearchInput } from "@/components/SearchInput";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-row">
          <NextAuthProvider>
            <SideBar />
            <div className="hidden">
              <FiltersButton />
            </div>
            <div className="flex flex-grow">{children}</div>
          </NextAuthProvider>
        </main>
      </body>
    </html>
  );
}
